// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function SetMuted(arg1, arg2) {
  return window['go']['main']['App']['SetMuted'](arg1, arg2);
}

export function SetVolume(arg1, arg2) {
  return window['go']['main']['App']['SetVolume'](arg1, arg2);
}
