// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetChannels():Promise<Array<models.Channel>>;

export function Greet(arg1:string):Promise<string>;

export function SetMute(arg1:number,arg2:boolean):Promise<void>;

export function SetVolume(arg1:number,arg2:number):Promise<void>;
